export interface Site {
  id: string;
  name: string;
  url: string;
  assigned: string;
  activeBranch: string;
  branches: string[];
  server: string;
  folderPath: string;
  commandOutput?: string;
}

export const initialSites: Site[] = [
  { id: '1',  name: 'colombianlady.com', url: 'http://colombianlady.cenix', assigned: 'afacebu.wilfredo@gmail.com', activeBranch: '', branches: ["loading"], server: 'sftp', folderPath: 'R:/WebServer2/colombianlady.com' },
  { id: '2',  name: 'barranquilladating.com', url: 'http://barranquilladating.cenix', assigned: 'afacebu.randy@gmail.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', folderPath: 'R:/WebServer2/barranquilladating.com' },
  { id: '3',  name: 'poltavawomen.com', url: 'http://poltavawomen.cenix', assigned: 'afacebu.jestoni@gmail.com', activeBranch: '', branches: ['loading'], server: 'ftp', folderPath: 'R:/WebServer2/poltavawomen.com' },
  { id: '4',  name: 'philippine-women.com', url: 'http://philippine-women.cenix', assigned: 'afacebu.wilfredo@gmail.com', activeBranch: '', branches: ['loading'], server: 'ftp', folderPath: 'R:/WebServer2/philippine-women.com' },
  { id: '5',  name: 'manila-women.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://manila-women.cenix', folderPath: 'R:/WebServer5/manila-women.com', assigned: 'afacebu.ayie@gmail.com', },
  { id: '6',  name: 'cartagenawomen.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://cartagenawomen.cenix', folderPath: 'R:/WebServer2/cartagenawomen.com', assigned: 'afacebu.ayie@gmail.com', },
  { id: '7',  name: 'cartagenadating.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://cartagenadating.cenix', folderPath: 'R:/WebServer2/cartagenadating.com', assigned: 'afacebu.ayie@gmail.com', },
  { id: '8',  name: 'cebuwomen.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://cebuwomen.cenix', folderPath: 'R:/WebServer2/cebuwomen.com', assigned: 'afacebu.ayie@gmail.com', },
  { id: '9',  name: 'filipino-women.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://filipino-women.cenix', folderPath: 'R:/WebServer5/filipino-women.com', assigned: 'afacebu.ayie@gmail.com', },
  { id: '10', name: 'filipino-bride.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://filipino-bride.cenix',folderPath: 'R:/WebServer5/filipino-bride.com',assigned: 'afacebu.ayie@gmail.com',},
  { id: '11', name: 'dateint.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://dateint.cenix',folderPath: 'R:/WebServers/dateint.com',assigned: 'afacebu.ayie@gmail.com',},
  { id: '12', name: 'latin-personals.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://latin-personals.cenix',folderPath: 'R:/WebServer3/latin-personals.com',assigned: 'afacebu.ayie@gmail.com',},
  { id: '13', name: 'international-dating.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://international-dating.cenix',folderPath: 'R:/WebServer5/international-dating.com',assigned: 'afacebu.ayie@gmail.com',},
  { id: '14', name: 'loveme.com',activeBranch: 'main', branches: ['loading'],server: 'ftp', url: 'http://loveme.cenix',folderPath: 'R:/WebServer2/loveme.com',assigned: 'afacebu.ayie@gmail.com',},
  { id: '15', name: 'china-brides.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://china-brides.cenix',folderPath: 'R:/WebServer5/china-brides.com',assigned: 'afacebu.jestoni@gmail.com',},
  { id: '16', name: 'barranquillasingles.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://barranquillasingles.cenix',folderPath: 'R:/WebServer2/barranquillasingles.com',assigned: 'afacebu.jestoni@gmail.com',},
  { id: '17', name: '1stlatinwomen.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://1stlatinwomen.cenix',folderPath: 'R:/WebServer2/1stlatinwomen.com',assigned: 'afacebu.jestoni@gmail.com',},
  { id: '18', name: 'asian-women.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://asian-women.cenix',folderPath: 'R:/WebServer5/asian-women.com',assigned: 'afacebu.jestoni@gmail.com',},
  { id: '19', name: 'honduraswomen.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://honduraswomen.cenix',folderPath: 'R:/WebServer2/honduraswomen.com',assigned: 'afacebu.jestoni@gmail.com',},
  { id: '20', name: 'islandladies.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://islandladies.cenix',folderPath: 'R:/WebServer5/islandladies.com',assigned: 'afacebu.abraham@gmail.com',},
  { id: '21', name: 'asianlovemates.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://asianlovemates.cenix',folderPath: 'R:/WebServer5/asianlovemates.com',assigned: 'afacebu.abraham@gmail.com',},
  { id: '22', name: 'anewbride.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://anewbride.cenix',folderPath: 'R:/WebServer2/anewbride.com',assigned: 'afacebu.abraham@gmail.com',},
  { id: '23', name: 'mexicanlovemates.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://mexicanlovemates.cenix',folderPath: 'R:/WebServer5/mexicanlovemates.com',assigned: 'afacebu.abraham@gmail.com',},
  { id: '24', name: 'a-foreign-affair.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://a-foreign-affair.cenix',folderPath: 'R:/WebServer2/a-foreign-affair.com',assigned: 'afacebu.abraham@gmail.com',},
  { id: '25', name: 'colombianwoman.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://colombianwoman.cenix',folderPath: 'R:/WebServer2/colombianwoman.com',assigned: 'afacebu.abraham@gmail.com',},
  { id: '26', name: 'bangkok-women.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://bangkok-women.cenix', folderPath: 'R:/WebServer2/bangkok-women.com', assigned: 'afacebu.joseanthony@gmail.com',},
  { id: '27', name: 'ukraineladies.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://ukraineladies.cenix', folderPath: 'R:/WebServer5/ukraineladies.com', assigned: 'afacebu.joseanthony@gmail.com',},
  { id: '28', name: 'costa-rica-women.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://costa-rica-women.cenix', folderPath: 'R:/WebServer2/costa-rica-women.com', assigned: 'afacebu.joseanthony@gmail.com',},
  { id: '29', name: 'medellinsingles.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://medellinsingles.cenix', folderPath: 'R:/WebServer3/medellinsingles.com', assigned: 'afacebu.joseanthony@gmail.com',},
  { id: '30', name: 'ukrainesingles.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://ukrainesingles.cenix', folderPath: 'R:/WebServer5/ukrainesingles.com', assigned: 'afacebu.joseanthony@gmail.com',},
  { id: '31', name: 'russia-ladies.com', activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://russia-ladies.cenix', folderPath: 'R:/WebServer2/russia-ladies.com', assigned: 'afacebu.joseanthony@gmail.com',},
  { id: '32', name: 'moscowladies.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://moscowladies.cenix',folderPath: 'R:/WebServer2/moscowladies.com',assigned: 'afacebu.wilfredo@gmail.com',},
  { id: '33', name: 'poltavawomen.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://poltavawomen.cenix',folderPath: 'R:/WebServer2/poltavawomen.com',assigned: 'afacebu.wilfredo@gmail.com',},
  { id: '34', name: 'colombianbride.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://colombianbride.cenix',folderPath: 'R:/c_women/colombianbride.com',assigned: 'afacebu.wilfredo@gmail.com',},
  { id: '35', name: 'foreignbride.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://foreignbride.cenix',folderPath: 'R:/c_affil/foreignbride.com',assigned: 'afacebu.wilfredo@gmail.com',},
  { id: '36', name: 'kievpersonals.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://kievpersonals.cenix',folderPath: 'R:/WebServer5/kievpersonals.com',assigned: 'afacebu.randy@gmail.com',},
  { id: '37', name: 'saint-petersburg-women.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://saint-petersburg-women.cenix',folderPath: 'R:/WebServer2/saint-petersburg-women.com',assigned: 'afacebu.randy@gmail.com',},
  { id: '38', name: 'cityofbrides.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://cityofbrides.cenix',folderPath: 'R:/WebServer2/cityofbrides.com',assigned: 'afacebu.randy@gmail.com',},
  { id: '39', name: 'foreignlovemates.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://foreignlovemates.cenix',folderPath: 'R:/WebServer5/foreignlovemates.com',assigned: 'afacebu.randy@gmail.com',},
  { id: '40', name: 'anewwife.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://anewwife.cenix',folderPath: 'R:/WebServer2/anewwife.com',assigned: 'afacebu.randy@gmail.com',},
  { id: '41', name: 'colombianmatch.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://colombianmatch.cenix',folderPath: 'R:/WebServersOffices/colombianmatch.com',assigned: 'afacebu.randy@gmail.com',},
  { id: '42', name: 'mydreamasian.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://mydreamasian.cenix',folderPath: 'R:/WebServer5/mydreamasian.com',assigned: 'afacebu.melmarx@gmail.com',},
  { id: '43', name: 'acapulcowomen.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://acapulcowomen.cenix',folderPath: 'R:/WebServer2/acapulcowomen.com',assigned: 'afacebu.melmarx@gmail.com',},
  { id: '44', name: 'mexico-women.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://mexico-women.cenix',folderPath: 'R:/WebServer5/mexico-women.com',assigned: 'afacebu.melmarx@gmail.com',},
  { id: '45', name: 'medellindating.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://medellindating.cenix',folderPath: 'R:/WebServer2/medellindating.com',assigned: 'afacebu.melmarx@gmail.com',},
  { id: '46', name: 'latinlovemates.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://latinlovemates.cenix',folderPath: 'R:/WebServer5/latinlovemates.com',assigned: 'afacebu.melmarx@gmail.com',},
  { id: '47', name: 'datefitgirls.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://datefitgirls.cenix',folderPath: 'R:/WebServersCharlie/datefitgirls.com',assigned: 'afacebu.melmarx@gmail.com',},
  { id: '48', name: 'singlewomenonline.com',activeBranch: 'main', branches: ['loading'], server: 'sftp', url: 'http://singlewomenonline.cenix',folderPath: 'R:/sftp/singlewomenonline.com',assigned: 'afacebu.melmarx@gmail.com',},
  { id: '49', name: 'afabangkok.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://afabangkok.cenix',folderPath: 'R:/WebServer5/afabangkok.com',assigned: 'afacebu.melmarx@gmail.com',},
  { id: '50', name: 'a-foreign-affair.net',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://a-foreign-affair.cenix',folderPath: 'R:/WebServer2/a-foreign-affair.net',assigned: 'cebu.devon@gmail.com',},
  { id: '51', name: 'colombianlady.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://colombianlady.cenix',folderPath: 'R:/WebServer2/colombianlady.com',assigned: 'cebu.devon@gmail.com',},
  { id: '52', name: 'barranquilladating.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://barranquilladating.cenix',folderPath: 'R:/WebServer2/barranquilladating.com',assigned: 'cebu.devon@gmail.com',},
  { id: '53', name: 'medellinwomen.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://medellinwomen.cenix',folderPath: 'R:/WebServer2/medellinwomen.com',assigned: 'cebu.devon@gmail.com',},
  { id: '54', name: 'perudating.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://perudating.cenix',folderPath: 'R:/c_affil/perudating.com',assigned: 'cebu.devon@gmail.com',},
  { id: '55', name: 'peru-women.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://peru-women.cenix',folderPath: 'R:/WebServer2/peru-women.com',assigned: 'cebu.devon@gmail.com',},
  { id: '56', name: 'davaowomen.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://davaowomen.cenix',folderPath: 'R:/WebServer5/davaowomen.com',assigned: 'afacebu.benjiebroa@gmail.com',},
  { id: '57', name: 'foreign-affair.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://foreign-affair.cenix',folderPath: 'R:/WebServer2/foreign-affair.net',assigned: 'afacebu.benjiebroa@gmail.com',},
  { id: '58', name: 'thailand-women.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://thailand-women.cenix',folderPath: 'R:/WebServer5/thailand-women.com',assigned: 'afacebu.benjiebroa@gmail.com',},
  { id: '59', name: 'shenzhenwomen.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://shenzhenwomen.cenix',folderPath: 'R:/WebServer2/shenzhenwomen',assigned: 'afacebu.benjiebroa@gmail.com',},
  { id: '60', name: '1stchoicedating.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://1stchoicedating.cenix',folderPath: 'R:/WebServer2/1stchoicedating.com',assigned: 'afacebu.benjiebroa@gmail.com',},
  { id: '61', name: 'hondurasdating.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://hondurasdating.cenix',folderPath: 'R:/WebServer2/hondurasdating.com',assigned: 'afacebu.benjiebroa@gmail.com',},
  { id: '62', name: 'russia-women.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://russia-women.cenix',folderPath: 'R:/WebServer2/russia-women.com',assigned: 'afacebu.yevgenygrazio@gmail.com',},
  { id: '63', name: 'colombiandating.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://colombiandating.cenix',folderPath: 'R:/c_affil/colombiandating.com',assigned: 'afacebu.yevgenygrazio@gmail.com',},
  { id: '64', name: 'mymailorderbride.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://mymailorderbride.cenix',folderPath: 'R:/WebServer2/mymailorderbride.com',assigned: 'afacebu.yevgenygrazio@gmail.com',},
  { id: '65', name: 'cali-women.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://cali-women.cenix',folderPath: 'R:/WebServer2/cali-women.com',assigned: 'afacebu.yevgenygrazio@gmail.com',},
  { id: '66', name: 'foreignladies.com',activeBranch: 'main', branches: ['loading'], server: 'sftp', url: 'http://foreignladies.cenix',folderPath: 'R:/sftp/foreignladies.com',assigned: 'afacebu.yevgenygrazio@gmail.com',},
  { id: '67', name: 'barranquillawomen.com',activeBranch: 'main', branches: ['loading'], server: 'ftp', url: 'http://barranquillawomen.cenix',folderPath: 'R:/WebServer2/barranquillawomen.com',assigned: 'afacebu.yevgenygrazio@gmail.com',},
  { id: '68', name: 'asialovemates.com',activeBranch: 'main', branches: ['loading'],  server: 'sftp',  url: 'http://asialovemates.cenix', folderPath: 'R:/sftp/asialovemates.com', assigned: 'afacebu.yevgenygrazio@gmail.com', },
  { id: '69',  name: 'worldlovemates.com', activeBranch: 'main',  branches: ['loading'],  server: 'sftp',  url: 'http://worldlovemates.cenix', folderPath: 'R:/sftp/worldlovemates.com', assigned: 'afacebu.yevgenygrazio@gmail.com', },
  { id: '70',  name: 'kievwomen.com', activeBranch: 'main',  branches: ['loading'],  server: 'ftp',  url: 'http://kievwomen.cenix', folderPath: 'R:/WebServer2/kievwomen.com', assigned: 'afacebu.aiujymphyap@gmail.com', },
  { id: '71',  name: 'mexicocitydating.com', activeBranch: 'main',  branches: ['loading'],  server: 'ftp',  url: 'http://mexicocitydating.cenix', folderPath: 'R:/WebServer5/mexicocitydating.com', assigned: 'afacebu.aiujymphyap@gmail.com', },
  { id: '72',  name: 'angelsofpassion.com', activeBranch: 'main',  branches: ['loading'],  server: 'ftp',  url: 'http://angelsofpassion.cenix', folderPath: 'R:/WebServer2/angelsofpassion.com', assigned: 'afacebu.aiujymphyap@gmail.com', },
  { id: '73',  name: 'shenzhendating.com', activeBranch: 'main',  branches: ['loading'],  server: 'ftp',  url: 'http://shenzhendating.cenix', folderPath: 'R:/WebServer2/shenzhendating.com', assigned: 'afacebu.aiujymphyap@gmail.com', },
  { id: '74',  name: 'shanghai-women.com', activeBranch: 'main',  branches: ['loading'],  server: 'ftp',  url: 'http://shanghai-women.cenix', folderPath: 'R:/WebServer5/shanghai-women.com', assigned: 'afacebu.aiujymphyap@gmail.com', },
  { id: '75',  name: 'odessawomen.com', activeBranch: 'main',  branches: ['loading'],  server: 'ftp',  url: 'http://odessawomen.cenix', folderPath: 'R:/WebServer5/odessawomen.com', assigned: 'afacebu.aiujymphyap@gmail.com', },
  { id: '76',  name: 'eurolovemates.com', activeBranch: 'main',  branches: ['loading'],  server: 'sftp',  url: 'http://eurolovemates.cenix', folderPath: 'R:/sftp/eurolovemates.com', assigned: 'afacebu.aiujymphyap@gmail.com', },
  { id: '77',  name: 'latinalovemates.com', activeBranch: 'main',  branches: ['loading'],  server: 'sftp',  url: 'http://latinalovemates.cenix', folderPath: 'R:/sftp/latinalovemates.com', assigned: 'afacebu.aiujymphyap@gmail.com', },
];
